theme: jekyll-theme-cayman
title: [سامانه مدیریت وام]
description: [سامانه ای برای دریافت و پرداخت اقساط وام + پنل مدیریت بانکدار]
show_downloads: ["true"]
github:
  zip_url: https://5ip.ir/debt/debt.zip
  Demo: https://5ip.ir/debt/
